# Cloud Build Configuration for AI Gatekeeper
# Automatically builds and deploys to Cloud Run

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ai-gatekeeper:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ai-gatekeeper:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ai-gatekeeper:$COMMIT_SHA'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ai-gatekeeper'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ai-gatekeeper:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '1000'
      - '--memory'
      - '8Gi'
      - '--cpu'
      - '4'
      - '--timeout'
      - '3600'
      - '--concurrency'
      - '10'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/ai-gatekeeper:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/ai-gatekeeper:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
